name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.x

      - name: Install test dependencies
        run: |
          python -m pip install nose2 coverage

      - name: Run tests
        run: |
          coverage run -m nose2

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1
